# Generated by Django 2.0.3 on 2018-05-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0002_auto_20180509_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.IntegerField(verbose_name='titulo')),
                ('descricao', models.CharField(max_length=3000, verbose_name='descricao')),
                ('conteudo', models.CharField(max_length=3000, verbose_name='conteudo')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
            ],
        ),
    ]
