# Generated by Django 2.0.3 on 2018-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0003_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade_Vinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=3, verbose_name='rotulo')),
                ('status_av', models.CharField(max_length=15, verbose_name='status_av')),
                ('Data_InicioRespostas', models.DateField(verbose_name='Data_InicioRespostas')),
                ('Data_FimRespostas', models.DateField(verbose_name='Data_FimRespostas')),
            ],
        ),
    ]
