# Generated by Django 2.0.3 on 2018-05-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0004_atividade_vinculada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='titulo')),
                ('resposta', models.CharField(max_length=3000, verbose_name='resposta')),
                ('data_entrega', models.DateField(verbose_name='data_entrega')),
                ('status_e', models.CharField(max_length=40, verbose_name='status_e')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='nota')),
                ('dt_avaliacao', models.DateField(verbose_name='dt_avaliacao')),
                ('obs', models.CharField(max_length=3000, verbose_name='obs')),
            ],
        ),
    ]
