# Generated by Django 2.0.3 on 2018-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='login')),
                ('senha', models.CharField(max_length=40, verbose_name='senha')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('celular', models.IntegerField(verbose_name='celular')),
                ('data_expiracao', models.DateField(verbose_name='data_expiracao')),
                ('ra', models.IntegerField(verbose_name='ra')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='login')),
                ('senha', models.CharField(max_length=50, verbose_name='senha')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('celular', models.CharField(max_length=50, verbose_name='celular')),
                ('data_expiracao', models.DateField(max_length=100, verbose_name='data_expiracao')),
                ('apelido', models.CharField(max_length=20, verbose_name='apelido')),
            ],
        ),
    ]
