# Generated by Django 2.0.3 on 2018-05-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('data_expiracao', models.DateField(verbose_name='data_expiracao')),
                ('status', models.CharField(max_length=10, verbose_name='status')),
                ('plano_ensino', models.CharField(max_length=3000, verbose_name='plano_ensino')),
                ('carga_horaria', models.IntegerField(verbose_name='carga_horaria')),
                ('competencias', models.CharField(max_length=3000, verbose_name='competencias')),
                ('habilidade', models.CharField(max_length=3000, verbose_name='habilidade')),
                ('ementa', models.CharField(max_length=3000, verbose_name='ementa')),
                ('conteudo_programatico', models.CharField(max_length=3000, verbose_name='conteudo_programatico')),
                ('bibliografia_basica', models.CharField(max_length=3000, verbose_name='bibliografia_basica')),
                ('bibliografia_complementar', models.CharField(max_length=3000, verbose_name='bibliografia_complementar')),
                ('percentual_pratico', models.IntegerField(verbose_name='percentual_pratico')),
                ('percentual_teorico', models.IntegerField(verbose_name='percentual_teorico')),
            ],
        ),
    ]
